### ISSUE TITLE
MVPレビュー

### ISSUE THREAD

**Issue by shurijoc** [haru248/LIVE_Planning#21]
こちらにレビュー内容書かせていただきます！
就活を踏まえて、以下の観点からサービスとREADMEを元にレビューさせていただきますね。

```
💡 就活レビュー観点

1. 課題に対してサービス内で適切な解決策となる機能を提供できているか・READMEに書いているか
2. 就活において十分な技術力を示せる機能を実装しているか
3. UIでユーザーが迷わないような導線を作れているか・ユーザーが使いたくなるようなサービス設計ができているか
```

## 1について

READMEで「課題・課題に対する仮説・仮説に対する解決策」をセットで提示することが大切です。
サービス利用者に対しても就活においても、サービスの機能に説得力がうまれるためです。

すでに課題と解決策は書いているので仮説を教えていただくことはできますか？

## 2について
Railsの基本的なCRUDとAPIという印象がありますので、1機能ほど追加する必要があるかと思います。
仮説部分を整理してから再度具体的なところは書かせていただきます！

## 3について
こちらも同じく仮説部分に答えていただいてからレビューさせていただきます！

以上、よろしくお願いいたします。

**Comment by haru248** [comment]
### 1について
・課題に対する仮説
 - 持ち物などを管理する方法が必要
 - 持ち物リストなどを無くしてしまうリスクや作成の手間などを減らす方法が必要

仮説の考え方がいまいちわからなかったのでこのような形になりましたが、どうでしょうか?ご確認お願いします。

**Comment by shurijoc** [comment]
> 持ち物などを管理する方法が必要
> 持ち物リストなどを無くしてしまうリスクや作成の手間などを減らす方法が必要

「作成の手間がかかっている」に対して「何が作成の手間なのか・どうすれば作成の手間を減らせるのか」というところを教えていただけますか？
例えばtrelloやnotionなどすでにリストをアプリで作成する手段はあるかと思います。
それらのような競合には何か足りないことがあるということでしょうか？

**Comment by haru248** [comment]
trelloやnotionを利用したことがないため、軽く調べた程度の知識しかないので間違いがあるかもしれませんがご了承ください。

このアプリの仕様を考える際に、他のスマホアプリ数種を実際に使用してみました。それらやtrelloやnotionでリストを作成する場合、一つのリストを作成する分には特に問題はないとは思いますが、実際は状況に応じて複数のリストを作成する場合があると思います(例えば日帰りで済む場合のリストと泊まりになる場合のリストなど)。そうした場合に複数リストを作成する場合に、それぞれ1から作成するとなると二度手間な部分などが発生すると思います。そうしたリストの重複した部分にかかる手間を解消するために何か使い回しの出来る機能を用意しようと考え、プリセット機能を作成することにしました。似たような機能を持つアプリも存在しましたが、デフォルトで用意されているものしか利用出来ないような自由度の低さだったため、自由にプリセットを作成でき、かつデフォルトのプリセットも用意し編集・削除も可能という形にしました。

**Comment by shurijoc** [comment]
@haru248 
他との差別化ポイントとしてプリセットの自由度のところがあるということですね。ありがとうございます！
1については内容承知いたしました。

2,3についてですが、サイトを見た際に使い方が分かりづらくユーザーの理想的な導線を最初のページ遷移時に表示することはできますか？
特に持ち物リスト詳細の「カテゴリー・プリセット・リスト」などのリンクが並んでいる箇所が、情報が横並びになりすぎていて初見のユーザーが迷ってしまうかと思います。
こちらに関しては一度このスライドを読んでいただくと方向性が見えてくるかと思います。
https://speakerdeck.com/monoooki/read-a-non-designers-designbook?slide=38

なので、
① 最初の遷移時に使い方3STEPのようなモーダルを表示する
② 持ち物リスト詳細のリンクの表示のコントラストを意識する（使用頻度などによって配置を変えるなど）

以上よろしくお願いいたします。

**Comment by haru248** [comment]
①各詳細ページに使用方法のモーダルを実装しました。初回アクセス時とページ右上の?ボタンクリック時に表示されるようにしました。初回アクセスかの確認にはlocal storageを使用したため、アカウント削除時にlocal storageに保存した内容を削除するようにしました。
[`5a1fcc6`](https://github.com/haru248/LIVE_Planning/pull/26/commits/5a1fcc651746b3639f45c52c531bceb8ec37ec11)

②持ち物リスト詳細ページの各リンクのボタンの表示については、スライドの内容の活かし方がいまいち分からなかったため自分なりに変えてみました。
まずリスト使用ボタンを緑色に変えて単体で右側に移動、画面サイズによって２つのボタングループが一列になっていたのを二列表示に固定しました。カテゴリーと持ち物の追加とプリセット使用のボタングループのボタンのサイズをある程度均一化するために文字数を調整しました。ボタンの並びに関しては、カテゴリー編集→持ち物の追加という動線のためカテゴリー編集を左側に、プリセットの使用は使用頻度はこの中で一番低いと考えたため右側に配置しました。
この変更で以前よりは見やすさが改善されたと考えています。
[`49a4373`](https://github.com/haru248/LIVE_Planning/pull/25/commits/49a437339019ef1636412c1ce3c618280db82f5c)
[`5a1fcc6`](https://github.com/haru248/LIVE_Planning/pull/26/commits/5a1fcc651746b3639f45c52c531bceb8ec37ec11)

**Comment by kerochelo** [comment]
@haru248 
確認しました！使い方モーダルなどよくなりましたね:+1:
他に少し気になる点があったので下記に挙げますね

- プリセット編集/削除のボタン位置はカテゴリ編集、持ち物追加とは距離を離したほうがいいですね
- 同じように持ち物リストや物品購入リストもリスト名自体の編集/削除と追加の導線も同じように離しておくといいですね

**Comment by haru248** [comment]
各詳細ページのボタングループ同士の距離を調整し距離を離しました。また、物販購入リスト詳細ページのボタンに関してはページサイズによって横並びになっていたのを他ページと同じ二列表示に変更しました。

**Comment by kerochelo** [comment]
@haru248 
いい感じになりました、LGTMです！
引き続き本リリースに向けて頑張ってください:tada:
